###############################################
###
##   File:   LaunchRequest.rb
##   Desc:   Missile Launch data
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class LaunchRequest < IseMessage
  def initialize
    super
    desc "Missile Launch data"
     item(:double, :time_)
     item(:ACE_UINT32, :unitID_)
  end
end
