###############################################
###
##   File:   LLA_Vehicle_State.rb
##   Desc:   Lat, Lon, Alt Vehicle Position State
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class LLA_Vehicle_State < IseMessage
  def initialize
    super
    desc "LLA Vehicle Position State - decimal radians for lat/lon and decimal meters for alt"
     item(:double, :time_)
     item(SamsonMath::Vec3(:double), :lla_)
     item(SamsonMath::Vec3(:double), :velocity_)
     item(SamsonMath::EulerAngles, :attitude_)
     item(:ACE_UINT32, :unitID_)
  end
end
