###############################################
###
##   File:   SrMeasuredTargetStates.rb
##   Desc:   Surveillance Radar Measured Target
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class SrMeasuredTargetStates < IseMessage
  def initialize
    super
    desc "Surveillance Radar Measured Target"
     item(:double, :time_)
     item(SamsonMath::Vec3(:double), :position_)
     item(:ACE_UINT32, :unitID_)
  end
end
