###############################################
###
##   File:   StkLaunchMissile.rb
##   Desc:   Tell STK to initialize a Missile Object and to fly it
##           frome its launch site to its impact point
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class StkLaunchMissile < IseMessage
  def initialize
    super
    desc "Initialize and Launch an STK Missile Object Model"
    item(:ascii_string32,           :label_)
    item(SamsonMath::Vec3(:double), :launch_position_)
    item(SamsonMath::Vec3(:double), :target_position_)
  end
end
