###############################################
###
##   File:   TargetDestroyed.rb
##   Desc:   Target Destroyed End Engagement
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class TargetDestroyed < IseMessage
  def initialize
    super
    desc "Target Destroyed End Engagement"
     item(:double, :time_)
     item(:bool, :state_)
     item(:ACE_UINT32, :unitID_)
  end
end
