###############################################
###
##   File:   TrkRadarMeasuredTargetStates.rb
##   Desc:   TRKRADAR Measured Position
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class TrkRadarMeasuredTargetStates < IseMessage
  def initialize
    super
    desc "TRKRADAR Measured Position"
     item(:double, :time_)
     item(SamsonMath::Vec3(:double), :position_)
     item(:ACE_UINT32, :unitID_)
  end
end
