###############################################
###
##   File:   TrkRadarUplink.rb
##   Desc:   TrkRadar Uplink
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class TrkRadarUplink < IseMessage
  def initialize
    super
    desc "TrkRadar Uplink"
     item(:double, :time_)
     item(SamsonMath::Vec3(:double), :position_)
     item(:ACE_UINT32, :unitID_)
  end
end
