###############################################
###
##   File:   TrkRadarOnCmd.rb
##   Desc:   TRKRADAR On data
##
##   This file was auto-generated by auto_code_msg_hpp_as_rb
#

require 'IseMessage'

class TrkRadarOnCmd < IseMessage
  def initialize
    super
    desc "TRKRADAR On data"
     item(:double, :time_)
     item(:bool, :on_)
     item(:ACE_UINT32, :unitID_)
  end
end
