#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (g++).
# Generated 09:52:56 AM 31 Jan 2007
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	g++
LD  	=	g++
WRES	=	windres
CCOMP	=	gcc
HOMEV	=	$(HOME)/v
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
libDirs	=	-L/usr/X11R6/lib

incDirs	=	-I/usr/X11R6/include \
	-I/home/sellshr/build4r003/table \
	-I/home/sellshr/build4r003/vec \
	-I/home/sellshr/build4r003/osk

LD_FLAGS =	
LIBS	=	
C_FLAGS	=	-O

SRCS	=\
	Element.cpp\
	Guide.cpp\
	Kinem.cpp\
	Missile.cpp\
	Output.cpp\
	Radar.cpp\
	RadarT.cpp\
	TFAtm.cpp\
	TFAtm59.cpp\
	TFAtm62.cpp\
	Target.cpp\
	fc.cpp\
	filer.cpp\
	main.cpp\
	util.cpp\
	/home/sellshr/build4r003/table/strtok.cpp\
	/home/sellshr/build4r003/table/table.cpp\
	/home/sellshr/build4r003/table/table1.cpp\
	/home/sellshr/build4r003/table/table2.cpp\
	/home/sellshr/build4r003/table/table3.cpp\
	/home/sellshr/build4r003/vec/mat.cpp\
	/home/sellshr/build4r003/vec/quat.cpp\
	/home/sellshr/build4r003/vec/vec.cpp\
	/home/sellshr/build4r003/osk/block.cpp\
	/home/sellshr/build4r003/osk/sim.cpp\
	/home/sellshr/build4r003/osk/state.cpp\
	/home/sellshr/build4r003/osk/state_euler.cpp\
	/home/sellshr/build4r003/osk/state_mm.cpp\
	/home/sellshr/build4r003/osk/state_rk2.cpp

EXOBJS	=\
	$(oDir)/Element.o\
	$(oDir)/Guide.o\
	$(oDir)/Kinem.o\
	$(oDir)/Missile.o\
	$(oDir)/Output.o\
	$(oDir)/Radar.o\
	$(oDir)/RadarT.o\
	$(oDir)/TFAtm.o\
	$(oDir)/TFAtm59.o\
	$(oDir)/TFAtm62.o\
	$(oDir)/Target.o\
	$(oDir)/fc.o\
	$(oDir)/filer.o\
	$(oDir)/main.o\
	$(oDir)/util.o\
	$(oDir)/strtok.o\
	$(oDir)/table.o\
	$(oDir)/table1.o\
	$(oDir)/table2.o\
	$(oDir)/table3.o\
	$(oDir)/mat.o\
	$(oDir)/quat.o\
	$(oDir)/vec.o\
	$(oDir)/block.o\
	$(oDir)/sim.o\
	$(oDir)/state.o\
	$(oDir)/state_euler.o\
	$(oDir)/state_mm.o\
	$(oDir)/state_rk2.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/linux
ALLTGT	=	$(Bin)/linux

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/linux: $(EXOBJS)
	$(LD) -o $(Bin)/linux $(EXOBJS) $(incDirs) $(libDirs) $(LD_FLAGS) $(LIBS)

$(oDir)/strtok.o: /home/sellshr/build4r003/table/strtok.cpp \
  /home/sellshr/build4r003/table/strtok.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/table.o: /home/sellshr/build4r003/table/table.cpp \
  /home/sellshr/build4r003/table/table.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/table1.o: /home/sellshr/build4r003/table/table1.cpp \
  /home/sellshr/build4r003/table/table1.h \
  /home/sellshr/build4r003/table/strtok.h \
  /home/sellshr/build4r003/table/table.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/table2.o: /home/sellshr/build4r003/table/table2.cpp \
  /home/sellshr/build4r003/table/table2.h \
  /home/sellshr/build4r003/table/strtok.h \
  /home/sellshr/build4r003/table/table.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/table3.o: /home/sellshr/build4r003/table/table3.cpp \
  /home/sellshr/build4r003/table/table3.h \
  /home/sellshr/build4r003/table/strtok.h \
  /home/sellshr/build4r003/table/table.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/mat.o: /home/sellshr/build4r003/vec/mat.cpp \
  /home/sellshr/build4r003/vec/mat.h /home/sellshr/build4r003/vec/vec.h \
  /home/sellshr/build4r003/vec/quat.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/quat.o: /home/sellshr/build4r003/vec/quat.cpp \
  /home/sellshr/build4r003/vec/quat.h /home/sellshr/build4r003/vec/mat.h \
  /home/sellshr/build4r003/vec/vec.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/vec.o: /home/sellshr/build4r003/vec/vec.cpp \
  /home/sellshr/build4r003/vec/vec.h /home/sellshr/build4r003/vec/mat.h \
  /home/sellshr/build4r003/vec/quat.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/block.o: /home/sellshr/build4r003/osk/block.cpp \
  /home/sellshr/build4r003/osk/block.h \
  /home/sellshr/build4r003/osk/state.h /home/sellshr/build4r003/osk/sim.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/sim.o: /home/sellshr/build4r003/osk/sim.cpp \
  /home/sellshr/build4r003/osk/sim.h /home/sellshr/build4r003/osk/block.h \
  /home/sellshr/build4r003/osk/state.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/state.o: /home/sellshr/build4r003/osk/state.cpp \
  /home/sellshr/build4r003/osk/state.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/state_euler.o: /home/sellshr/build4r003/osk/state_euler.cpp \
  /home/sellshr/build4r003/osk/state_euler.h \
  /home/sellshr/build4r003/osk/state.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/state_mm.o: /home/sellshr/build4r003/osk/state_mm.cpp \
  /home/sellshr/build4r003/osk/state_mm.h \
  /home/sellshr/build4r003/osk/state.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/state_rk2.o: /home/sellshr/build4r003/osk/state_rk2.cpp \
  /home/sellshr/build4r003/osk/state_rk2.h \
  /home/sellshr/build4r003/osk/state.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
