# File: test_GeoDatum.rb
# Code Generated by ZenTest v. 4.1.4

require 'pp'
require 'GeoDatum'
require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__

class TestGeoDatum < Test::Unit::TestCase

#  def test_class_dump
#    raise NotImplementedError, 'Need to write test_class_dump'
#  end


  def test_class_get
    assert_raise(NameError) { GeoDatum.get('xyzzy') }
    assert_nothing_raised(Exception) do
      GeoDatum.get('wgs84')
    end
    wgs84 = GeoDatum.get('wgs84')
    wgs84.each_pair do |k,v|
      instance_value = eval "WGS84.#{k}"
      assert instance_value == v, "WGS84.#{k} should be #{v}"
    end
  end

=begin
  def test_class_list
    raise NotImplementedError, 'Need to write test_class_list'
  end

  def test_a
    raise NotImplementedError, 'Need to write test_a'
  end

  def test_a_equals
    raise NotImplementedError, 'Need to write test_a_equals'
  end

  def test_b
    raise NotImplementedError, 'Need to write test_b'
  end

  def test_b_equals
    raise NotImplementedError, 'Need to write test_b_equals'
  end

  def test_desc
    raise NotImplementedError, 'Need to write test_desc'
  end

  def test_desc_equals
    raise NotImplementedError, 'Need to write test_desc_equals'
  end

  def test_e
    raise NotImplementedError, 'Need to write test_e'
  end

  def test_e2
    raise NotImplementedError, 'Need to write test_e2'
  end

  def test_e2_equals
    raise NotImplementedError, 'Need to write test_e2_equals'
  end

  def test_e_equals
    raise NotImplementedError, 'Need to write test_e_equals'
  end

  def test_f
    raise NotImplementedError, 'Need to write test_f'
  end

  def test_f_equals
    raise NotImplementedError, 'Need to write test_f_equals'
  end

  def test_f_inv
    raise NotImplementedError, 'Need to write test_f_inv'
  end

  def test_f_inv_equals
    raise NotImplementedError, 'Need to write test_f_inv_equals'
  end

  def test_name_equals
    raise NotImplementedError, 'Need to write test_name_equals'
  end
=end

end ## end of class TestGeoDatum < Test::Unit::TestCase

